on:
  pull_request:
  push:
   branches:
     - main
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build-sample-project:
    name: Build and test project
    strategy:
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 5.1.x

      fail-fast: false
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext: false

      - name: Install all deps
        run: make install

      - name: Build everything
        run: make build

      - name: Test
        run: make test

      - name: Build example
        run: make build-example

      - name: Deploy (Linux only)
        if: github.ref == 'refs/heads/main' && matrix.system == 'ubuntu-latest'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/build
